import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Amirmohammad Eftekhari
 */
public class mainFrame extends javax.swing.JFrame { 
    /**
     * Creates new form TypingPractice_GUI
     */
    public mainFrame() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lbl1 = new javax.swing.JLabel();
        slider1 = new javax.swing.JSlider();
        lbl2 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        lbl4 = new javax.swing.JLabel();
        togglebtn1 = new javax.swing.JToggleButton();
        togglebtn2 = new javax.swing.JToggleButton();
        checkbox1 = new javax.swing.JCheckBox();
        checkbox2 = new javax.swing.JCheckBox();
        checkbox3 = new javax.swing.JCheckBox();
        checkbox4 = new javax.swing.JCheckBox();
        checkbox5 = new javax.swing.JCheckBox();
        jSeparator2 = new javax.swing.JSeparator();
        lbl5 = new javax.swing.JLabel();
        radiobtn1 = new javax.swing.JRadioButton();
        radiobtn2 = new javax.swing.JRadioButton();
        radiobtn3 = new javax.swing.JRadioButton();
        btn1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TippSpeed");
        setFocusable(false);
        setResizable(false);

        lbl1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl1.setText("Select the difficulty level of the text :");
        lbl1.setFocusable(false);
        lbl1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        slider1.setMaximum(3);
        slider1.setMinimum(1);
        slider1.setPaintLabels(true);
        slider1.setPaintTicks(true);
        slider1.setSnapToTicks(true);
        slider1.setToolTipText("");
        slider1.setValue(1);
        slider1.setFocusable(false);
        slider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slider1StateChanged(evt);
            }
        });

        lbl2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl2.setText("Easy");
        lbl2.setFocusable(false);

        lbl3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl3.setText("Medium");
        lbl3.setFocusable(false);

        lbl4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl4.setText("Hard");
        lbl4.setFocusable(false);

        togglebtn1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        togglebtn1.setSelected(true);
        togglebtn1.setText("Auto");
        togglebtn1.setFocusable(false);
        togglebtn1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                togglebtn1StateChanged(evt);
            }
        });
        togglebtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                togglebtn1ActionPerformed(evt);
            }
        });

        togglebtn2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        togglebtn2.setText("Customize");
        togglebtn2.setFocusable(false);
        togglebtn2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                togglebtn2StateChanged(evt);
            }
        });
        togglebtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                togglebtn2ActionPerformed(evt);
            }
        });

        checkbox1.setSelected(true);
        checkbox1.setText("Uppercase");
        checkbox1.setEnabled(false);
        checkbox1.setFocusable(false);

        checkbox2.setSelected(true);
        checkbox2.setText("Lowercase");
        checkbox2.setEnabled(false);
        checkbox2.setFocusable(false);

        checkbox3.setText("Numbers");
        checkbox3.setEnabled(false);
        checkbox3.setFocusable(false);

        checkbox4.setText("Marks");
        checkbox4.setEnabled(false);
        checkbox4.setFocusable(false);

        checkbox5.setText("Traps");
        checkbox5.setEnabled(false);
        checkbox5.setFocusable(false);

        lbl5.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lbl5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl5.setText("Select the typing duration :");
        lbl5.setFocusable(false);
        lbl5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        buttonGroup1.add(radiobtn1);
        radiobtn1.setSelected(true);
        radiobtn1.setText("30 s");
        radiobtn1.setFocusable(false);

        buttonGroup1.add(radiobtn2);
        radiobtn2.setText("60 s");
        radiobtn2.setFocusable(false);

        buttonGroup1.add(radiobtn3);
        radiobtn3.setText("120 s");
        radiobtn3.setFocusable(false);

        btn1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn1.setText("Start");
        btn1.setFocusable(false);
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(radiobtn1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(radiobtn2)
                        .addGap(125, 125, 125)
                        .addComponent(radiobtn3))
                    .addComponent(btn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(checkbox5))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(togglebtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbl2)
                                        .addGap(96, 96, 96)
                                        .addComponent(lbl3)
                                        .addGap(93, 93, 93)
                                        .addComponent(lbl4))
                                    .addComponent(slider1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(togglebtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(checkbox1)
                                    .addComponent(checkbox2))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(checkbox3)
                                    .addComponent(checkbox4))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl1)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(togglebtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(slider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl2)
                            .addComponent(lbl3)
                            .addComponent(lbl4))))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(togglebtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(checkbox1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(checkbox2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(checkbox3)
                            .addComponent(checkbox5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(checkbox4)))
                .addGap(31, 31, 31)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl5)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radiobtn1)
                    .addComponent(radiobtn2)
                    .addComponent(radiobtn3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleName("TippSpeed");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void togglebtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_togglebtn2ActionPerformed
        checkbox1.setEnabled(true);
        checkbox2.setEnabled(true);
        checkbox3.setEnabled(true);
        checkbox4.setEnabled(true);
        checkbox5.setEnabled(true);
        slider1.setEnabled(false);
        lbl2.setEnabled(false);
        lbl3.setEnabled(false);
        lbl4.setEnabled(false);
    }//GEN-LAST:event_togglebtn2ActionPerformed

    private void togglebtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_togglebtn1ActionPerformed
        checkbox1.setEnabled(false);
        checkbox2.setEnabled(false);
        checkbox3.setEnabled(false);
        checkbox4.setEnabled(false);
        checkbox5.setEnabled(false);
        if (slider1.getValue() == 1){
            checkbox1.setSelected(true);
            checkbox2.setSelected(true);
            checkbox3.setSelected(false);
            checkbox4.setSelected(false);
            checkbox5.setSelected(false);
        }
        if (slider1.getValue() == 2){
            checkbox1.setSelected(true);
            checkbox2.setSelected(true);
            checkbox3.setSelected(true);
            checkbox4.setSelected(true);
            checkbox5.setSelected(false);
        }
        if (slider1.getValue() == 3){
            checkbox1.setSelected(true);
            checkbox2.setSelected(true);
            checkbox3.setSelected(true);
            checkbox4.setSelected(true);
            checkbox5.setSelected(true);
        }
        slider1.setEnabled(true);
        lbl2.setEnabled(true);
        lbl3.setEnabled(true);
        lbl4.setEnabled(true);
    }//GEN-LAST:event_togglebtn1ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        
        int typeduration;
        if (radiobtn1.isSelected()){
            typeduration = 0;
        }else if (radiobtn2.isSelected()){
            typeduration = 1;
        }else{
            typeduration = 2;
        }
        settingClass SettingClass = new settingClass();
        SettingClass.Timer(typeduration);
        // Getting Typeduration Settings
        
        if (togglebtn1.isSelected()){
            int difficulty = slider1.getValue();
            this.setVisible(false);
            try {
                SettingClass.SecondFrame();
            } catch (InterruptedException ex) {
                Logger.getLogger(mainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            SettingClass.TextCreatation(difficulty);
            } // Getting Togglebtn1 Settings (If Selected)
        
        else{
                boolean uppercase = false;
                boolean lowercase = false;
                boolean numbers = false;
                boolean marks = false;
                boolean traps = false;

                if (checkbox1.isSelected()){
                    uppercase = true;
                }
                if (checkbox2.isSelected()){
                    lowercase = true;
                }
                if (checkbox3.isSelected()){
                    numbers = true;
                }
                if (checkbox4.isSelected()){
                    marks = true;
                }
                if (checkbox5.isSelected()){
                    traps = true;
                } 
                
            if (uppercase == false && lowercase == false &&
                numbers == false && marks == false &&
                traps == false){
                JOptionPane.showMessageDialog(null, "You must select at least one item of text difficulty !");
            }else{
                this.setVisible(false);
                    try {
                        SettingClass.SecondFrame();
                    } catch (InterruptedException ex) {
                        Logger.getLogger(mainFrame.class.getName()).log(Level.SEVERE, null, ex);
                    }
                SettingClass.TextCreatation(uppercase, lowercase, numbers, marks, traps);
               }
            } // Getting Togglebtn2 Settings (If Selected)
        
        

        
    }//GEN-LAST:event_btn1ActionPerformed

    private void slider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slider1StateChanged
        
        if (slider1.getValue() == 1){
            checkbox1.setSelected(true);
            checkbox2.setSelected(true);
            checkbox3.setSelected(false);
            checkbox4.setSelected(false);
            checkbox5.setSelected(false);
        }
        if (slider1.getValue() == 2){
            checkbox1.setSelected(true);
            checkbox2.setSelected(true);
            checkbox3.setSelected(true);
            checkbox4.setSelected(true);
            checkbox5.setSelected(false);
        }
        if (slider1.getValue() == 3){
            checkbox1.setSelected(true);
            checkbox2.setSelected(true);
            checkbox3.setSelected(true);
            checkbox4.setSelected(true);
            checkbox5.setSelected(true);
        }
        
    }//GEN-LAST:event_slider1StateChanged

    private void togglebtn1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_togglebtn1StateChanged
        togglebtn2.setSelected(false);
        if (togglebtn1.isSelected() == false && togglebtn2.isSelected() == false){
            togglebtn1.setSelected(true);
        }
    }//GEN-LAST:event_togglebtn1StateChanged

    private void togglebtn2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_togglebtn2StateChanged
        togglebtn1.setSelected(false);
        if (togglebtn1.isSelected() == false && togglebtn2.isSelected() == false){
            togglebtn2.setSelected(true);
        } 
    }//GEN-LAST:event_togglebtn2StateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new mainFrame().setVisible(true);
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btn1;
    private javax.swing.ButtonGroup buttonGroup1;
    public static javax.swing.JCheckBox checkbox1;
    public static javax.swing.JCheckBox checkbox2;
    public static javax.swing.JCheckBox checkbox3;
    public static javax.swing.JCheckBox checkbox4;
    public static javax.swing.JCheckBox checkbox5;
    public static javax.swing.JSeparator jSeparator2;
    public static javax.swing.JLabel lbl1;
    public static javax.swing.JLabel lbl2;
    public static javax.swing.JLabel lbl3;
    public static javax.swing.JLabel lbl4;
    public static javax.swing.JLabel lbl5;
    public static javax.swing.JRadioButton radiobtn1;
    public static javax.swing.JRadioButton radiobtn2;
    public static javax.swing.JRadioButton radiobtn3;
    public static javax.swing.JSlider slider1;
    public static javax.swing.JToggleButton togglebtn1;
    public static javax.swing.JToggleButton togglebtn2;
    // End of variables declaration//GEN-END:variables
}
