import java.util.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Amirmohammad Eftekhari
 */
public class typingFrame extends javax.swing.JFrame {

   private javax.swing.Timer countdown;
   private int remainingSeconds = settingClass.Sec;
    
    /**
     * Creates new form TextFrame
     */
    public typingFrame() {
        initComponents();
        
        formattedtext1.setText(formatHMS(remainingSeconds));
        this.addComponentListener(new java.awt.event.ComponentAdapter() {
        @Override
        public void componentShown(java.awt.event.ComponentEvent e) {
            startCountdown();
        }

        });
        
    }
    
public void setRemainingSeconds(int seconds) {
    remainingSeconds = Math.max(0, seconds);
    formattedtext1.setText(formatHMS(remainingSeconds));
}

private void startCountdown() {
    if (countdown != null && countdown.isRunning()) return;

    countdown = new javax.swing.Timer(1000, e -> {
        remainingSeconds--;
        formattedtext1.setText(formatHMS(remainingSeconds));

        if (remainingSeconds <= 0) {
            ((javax.swing.Timer) e.getSource()).stop();
            textarea1.setEditable(false);
            btn2.setText("Close");
        }
    });

    countdown.setInitialDelay(1000);
    countdown.start();
}

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        textarea1 = new javax.swing.JTextArea();
        formattedtext1 = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        textpane1 = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TippSpeed");
        setFocusable(false);
        setResizable(false);

        btn2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn2.setForeground(new java.awt.Color(255, 51, 51));
        btn2.setText("Cancel");
        btn2.setFocusable(false);
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        textarea1.setColumns(20);
        textarea1.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        textarea1.setLineWrap(true);
        textarea1.setRows(5);
        textarea1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        textarea1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textarea1KeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(textarea1);

        formattedtext1.setEditable(false);
        formattedtext1.setBackground(new java.awt.Color(255, 255, 255));
        formattedtext1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("mm:ss"))));
        formattedtext1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        formattedtext1.setFocusable(false);
        formattedtext1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N

        textpane1.setEditable(false);
        textpane1.setBackground(new java.awt.Color(0, 0, 0));
        textpane1.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        textpane1.setForeground(new java.awt.Color(255, 255, 255));
        textpane1.setFocusable(false);
        jScrollPane1.setViewportView(textpane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(formattedtext1)
                    .addComponent(btn2, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 526, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(formattedtext1, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        if (countdown != null && countdown.isRunning()) {
            countdown.stop();
        }
        this.setVisible(false);
        mainFrame SettingFrame = new mainFrame ();
        SettingFrame.setVisible(true);
    }//GEN-LAST:event_btn2ActionPerformed

    private void textarea1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textarea1KeyReleased
        
        TextControllerClass.GreenRedColorClass();

        ArrayList<String> InputChar = new ArrayList<>();
        InputChar.add(String.valueOf(evt.getKeyCode()));
        if (InputChar.lastIndexOf("8") == 0){
            TextControllerClass.WhiteColorClass();
        }

    }//GEN-LAST:event_textarea1KeyReleased
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(typingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new typingFrame().setVisible(true);
        });
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btn2;
    public static javax.swing.JFormattedTextField formattedtext1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTextArea textarea1;
    public static javax.swing.JTextPane textpane1;
    // End of variables declaration//GEN-END:variables

    private static String formatHMS(int totalSeconds) {
    int t = Math.max(0, totalSeconds);
    int h = t / 3600;
    int m = (t % 3600) / 60;
    int s = t % 60;
    return String.format("%02d:%02d:%02d", h, m, s);
    }
}
